# Generated by Django 5.0.6 on 2024-06-08 09:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpostlike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpostlike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
